-- Replace factory/HQ/viewer roles with Manager, Finance, Logistics.
CREATE TYPE "UserRole_new" AS ENUM ('SUPER_ADMIN', 'MANAGER', 'FINANCE', 'LOGISTICS');

ALTER TABLE "User" ALTER COLUMN "role" DROP DEFAULT;

ALTER TABLE "User" ALTER COLUMN "role" TYPE "UserRole_new" USING (
  CASE "role"::text
    WHEN 'SUPER_ADMIN' THEN 'SUPER_ADMIN'
    WHEN 'HQ_SALES' THEN 'FINANCE'
    WHEN 'LOGISTICS' THEN 'LOGISTICS'
    WHEN 'UAE_JEBEL_ALI' THEN 'MANAGER'
    WHEN 'UAE_SHARJAH' THEN 'MANAGER'
    WHEN 'UAE_ABU_DHABI' THEN 'MANAGER'
    WHEN 'VIEWER' THEN 'MANAGER'
    ELSE 'MANAGER'
  END
)::"UserRole_new";

DROP TYPE "UserRole";
ALTER TYPE "UserRole_new" RENAME TO "UserRole";

ALTER TABLE "User" ALTER COLUMN "role" SET DEFAULT 'MANAGER';
