-- AlterTable
ALTER TABLE "AppConfig" ADD COLUMN     "m2PerContainer" DOUBLE PRECISION DEFAULT 8300,
ADD COLUMN     "m2PerLinePerDay" DOUBLE PRECISION DEFAULT 3000,
ADD COLUMN     "productionLines" INTEGER DEFAULT 2,
ADD COLUMN     "workingDaysPerMonth" INTEGER DEFAULT 26;

